postgres:
  Host: localhost
  Port: 5432
  User: postgres
  Password: postgres
  Dbname: groqdb
  MaxOpenConns: 10
  MaxIdleConns: 10
  ConfMaxLifetime: 10
  ConnMaxIdleTime: 10
  ReadTimeout: 10
  WriteTimeout: 10
  PgDriver: pgx

server:
  address: 8080